server:
  port : 8081

spring:
  datasource:
    case:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/bjcase?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: yqx1989254
      hikari:
        minimum-idle: 10  #最小空闲连接数
        maximum-pool-size: 10 #最大连接数

    ssm:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: yqx1989254
      hikari:
        minimum-idle: 10
        maximum-pool-size: 10

  mybatis:
    config-location: classpath:mybatis-config.xml
    mapper-location: classpath:mapper/*.xml
    type-aliases-package: cn.iocoder.springboot.lab12.mybatis.dataobject